# Answering Business Questions using SQL

We will use the chinook database for this project. The chinook database is provided as a SQLite database file called chinook.db.

![](chinook-schema.svg)

In [34]:
from sqlalchemy.engine import create_engine
import sqlite3
from pandas.io import sql
import subprocess
%reload_ext sql

In [35]:
%sql sqlite:///chinook.db

'Connected: @chinook.db'

## Overview of the Data

Let us start by getting familiar with the data

In [36]:
%%sql
SELECT 
     name,
     type
FROM sqlite_master
WHERE type IN ('table','view');

 * sqlite:///chinook.db
Done.

[('albums', 'table'),
 ('sqlite_sequence', 'table'),
 ('artists', 'table'),
 ('customers', 'table'),
 ('employees', 'table'),
 ('genres', 'table'),
 ('invoices', 'table'),
 ('invoice_items', 'table'),
 ('media_types', 'table'),
 ('playlists', 'table'),
 ('playlist_track', 'table'),
 ('tracks', 'table'),
 ('sqlite_stat1', 'table')]

## Selecting Albums to Purchase

The Chinook record store has just signed a deal with a new record label, and the task is selecting the first three albums that will be added to the store, from a list of four. All four albums are by artists that do not have any tracks in the store right now - we have the artist names, and the genre of the music they produce.
|Artist | Genre |
|:----------:|:----------:|
|Regal | Hip-hop|
|Red Tone | Punk|
|Meteor and The Girls | Pop|
|Slim Jim Bites |Blues|

The record label specializes in artists from the USA, and they have given Chinook some money to advertise new albums in the USA, so we are interested in finding out which genres sell the best in the USA.

In [37]:
%%sql
WITH genre_sold_usa AS
(
    SELECT 
       g.Name genre,
       SUM(il.Quantity) num_tracks
      FROM genres g
      INNER JOIN tracks t on t.GenreId = g.GenreId
      INNER JOIN invoice_items il on il.TrackId = t.TrackId
      INNER JOIN invoices i on i.InvoiceId = il.InvoiceId
      INNER JOIN customers c on c.CustomerId = i.CustomerId
     WHERE c.country = 'USA'
     GROUP BY 1
     ORDER BY 2
)

SELECT 
    gsu.genre Genre,
    gsu.num_tracks abs_tracks
FROM genre_sold_usa gsu;

 * sqlite:///chinook.db
Done.

[('Science Fiction', 1),
 ('Easy Listening', 3),
 ('Rock And Roll', 3),
 ('Heavy Metal', 4),
 ('Hip Hop/Rap', 4),
 ('Soundtrack', 4),
 ('Alternative', 5),
 ('Pop', 5),
 ('Sci Fi & Fantasy', 5),
 ('Drama', 6),
 ('Reggae', 6),
 ('Bossa Nova', 7),
 ('Classical', 8),
 ('Comedy', 8),
 ('R&B/Soul', 12),
 ('TV Shows', 14),
 ('Blues', 15),
 ('Jazz', 22),
 ('Alternative & Punk', 50),
 ('Metal', 64),
 ('Latin', 91),
 ('Rock', 157)]

From the above, it can be said that Rock sells best in the USA, with a total of 157 tracks sold so far. However, Rock is not available in the record label.
Below is a list of the number of tracks sold according to the genres available in the record label, in a decreasing order, on the basis of no. of tracks sold.
1. Alternative & Punk - 50
2. Blues - 15
3. Pop - 5
4. Hip Hop/Rap - 4

Based on the list, we should purchase the albums of artists Red Tone, Slim Jim Bites, and Meteor and The Girls respectively, since their genres sell well.

## Analyzing Employee Sales Performace

Each customer for the Chinook store gets assigned to a sales support agent within the company when they first make a purchase. We have been asked to analyze the purchases of customers belonging to each employee to see if any sales support agent is performing either better or worse than the others.

In [38]:
%%sql

SELECT 
   e.FirstName || ' ' || e.LastName name,
   e.Title Title,
   e.BirthDate Birth_Date,
   e.HireDate Hire_Date,
   max(i.InvoiceDate) Latest_invoice_date,
   ROUND(SUM(i.Total), 2) amount_sales
  FROM employees e
  LEFT JOIN customers c on e.EmployeeId = c.SupportRepId
  LEFT JOIN invoices i on i.CustomerId = c.CustomerId

  WHERE Title = 'Sales Support Agent'
  GROUP BY 1
  ORDER BY 2

 * sqlite:///chinook.db
Done.

[('Jane Peacock', 'Sales Support Agent', '1973-08-29 00:00:00', '2002-04-01 00:00:00', '2013-12-22 00:00:00', 833.04),
 ('Margaret Park', 'Sales Support Agent', '1947-09-19 00:00:00', '2003-05-03 00:00:00', '2013-12-09 00:00:00', 775.4),
 ('Steve Johnson', 'Sales Support Agent', '1965-03-03 00:00:00', '2003-10-17 00:00:00', '2013-12-05 00:00:00', 720.16)]

## Analyzing Sales by Country

The next task is to analyze the sales data for customers from each country. The country value from customers table will be used for this analysis, and ignore the country from the billing address in the invoice table.

We should calculate data for each country on the
- total number of customers
- total value of sales
- average value of sales per customer
- average order value

Since there are a number of countries with only one customer, these customers should be grouped as "Other" in the analysis.

In [39]:
%%sql

WITH no_of_cstmrs AS
(
    SELECT 
       country Country,
       count(FirstName) No_of_customers
     FROM customers
      GROUP BY 1
      ORDER BY 2 DESC
)

SELECT * FROM no_of_cstmrs

 * sqlite:///chinook.db
Done.

[('USA', 13),
 ('Canada', 8),
 ('France', 5),
 ('Brazil', 5),
 ('Germany', 4),
 ('United Kingdom', 3),
 ('Portugal', 2),
 ('India', 2),
 ('Czech Republic', 2),
 ('Sweden', 1),
 ('Spain', 1),
 ('Poland', 1),
 ('Norway', 1),
 ('Netherlands', 1),
 ('Italy', 1),
 ('Ireland', 1),
 ('Hungary', 1),
 ('Finland', 1),
 ('Denmark', 1),
 ('Chile', 1),
 ('Belgium', 1),
 ('Austria', 1),
 ('Australia', 1),
 ('Argentina', 1)]

In [40]:
%%sql

WITH no_of_cstmrs AS
(
    SELECT 
       country Country,
       count(FirstName) No_of_customers
     FROM customers
      GROUP BY 1
      ORDER BY 2 DESC
),

total_sales_value AS
(SELECT c.country Country,
       ROUND(SUM(i.total), 2) Total_Value_Sales,
       ROUND(AVG(i.total), 2) Avg_Order_Value,
       ROUND(SUM(i.total)/(SELECT COUNT(DISTINCT(CustomerId)) FROM invoices), 2) Avg_Sales_Value_per_Customer
 
 FROM customers c
INNER JOIN invoices i ON i.CustomerId = c.CustomerId
GROUP BY 1
ORDER BY 2 DESC),

sales_data_1 AS
(SELECT noc.Country,
       noc.No_of_customers,
       tsv.Total_Value_Sales,
       tsv.Avg_Sales_Value_per_Customer,
       tsv.Avg_Order_Value
  FROM no_of_cstmrs noc  
INNER JOIN total_sales_value tsv ON tsv.Country=noc.Country
 WHERE noc.No_of_customers > 1),

sales_data_2 AS
(SELECT CASE
       WHEN noc.No_of_customers=1 THEN "Others"
       END AS
       Country,
       noc.No_of_customers,
       ROUND(AVG(tsv.Total_Value_Sales),2) Total_Value_Sales,
       ROUND(AVG(tsv.Avg_Sales_Value_per_Customer),2) AVG_Sales_Value_per_Customer,
       ROUND(AVG(tsv.Avg_Order_Value),2) AVG_Order_Value
  FROM no_of_cstmrs noc  
INNER JOIN total_sales_value tsv ON tsv.Country=noc.Country
 WHERE noc.No_of_customers = 1),

total_sales_data AS
(SELECT * 
FROM sales_data_1
UNION
SELECT * 
FROM sales_data_2)

SELECT *
  FROM total_sales_data
ORDER BY 3 DESC;

 * sqlite:///chinook.db
Done.

[('USA', 13, 523.06, 8.87, 5.75),
 ('Canada', 8, 303.96, 5.15, 5.43),
 ('France', 5, 195.1, 3.31, 5.57),
 ('Brazil', 5, 190.1, 3.22, 5.43),
 ('Germany', 4, 156.48, 2.65, 5.59),
 ('United Kingdom', 3, 112.86, 1.91, 5.37),
 ('Czech Republic', 2, 90.24, 1.53, 6.45),
 ('Portugal', 2, 77.24, 1.31, 5.52),
 ('India', 2, 75.26, 1.28, 5.79),
 ('Others', 1, 40.29, 0.68, 5.75)]

## Albums vs Individual Tracks

The Chinook store is setup in a way that allows customer to make purchases in one of the two ways:
- purchase a whole album
- purchase a collection of one or more individual tracks

The store does not let customers purchase a whole album, and then add individuals tracks to the same purchase (unless they do that by choosing each track manually). When customers purchase albums they are charged the same price as if they had purchased each of those tracks separately.

Management are currently considering changing their purchase strategy to save money. The strategy considered is to purchase only the most popular tracks from each album from record companies, instead of purchasing every track from an album.

We have to find out what percentage of purchases are individual tracks vs whole albums, so that management can use this data to understand the effect this decision might have on overall revenue.

It is quite common to have "edge cases" which prevent us from getting a 100% accurate answer to the question. In this instance, we have two edge cases to consider:
- Albums that have only one or two tracks are likely to be purchased by customers as part of a collection of individual tracks.
- Customers may decide to manually select every track from an album, and then add a few individual tracks from other albums to the purchase.

In the first case, since the analysis is concerned with maximizing revenue, we can safely ignore albums consisting of a few tracks. The company has previously done analysis to confirm that the second case does not happen often, so we can ignore this also.

In order to answer the question, we are going to have to identify whether each invoice has all the tracks from an album. We can do this by getting the list of tracks from an invoice and comparing it to the list of tracks from an album. We can find the album to compare the purchase to by looking up the album that one of the purchased tracks belongs to. It doesn't matter which track we pick, since if it's an album purchase, that album will be same for all tracks.

In [41]:
%%sql

SELECT max(InvoiceId) total_invoice
    FROM invoice_items;

 * sqlite:///chinook.db
Done.

[(412,)]

From the above table we observe that there are a total of 412 invoices. Further, we can compare the tracks from invoice with that of albums

In [42]:
%%sql

WITH com_prchs AS
(
    SELECT 
       il.InvoiceId invoice_id, 
       il.TrackId Prchs_tracks, 
       t.AlbumId album_id
      FROM tracks t
    INNER JOIN invoice_items il on il.TrackId = t.TrackId
    ORDER BY 1
)

SELECT *
 FROM com_prchs;

 * sqlite:///chinook.db
Done.

[(1, 2, 2),
 (1, 4, 3),
 (2, 6, 1),
 (2, 8, 1),
 (2, 10, 1),
 (2, 12, 1),
 (3, 16, 4),
 (3, 20, 4),
 (3, 24, 5),
 (3, 28, 5),
 (3, 32, 5),
 (3, 36, 5),
 (4, 42, 6),
 (4, 48, 6),
 (4, 54, 7),
 (4, 60, 7),
 (4, 66, 8),
 (4, 72, 8),
 (4, 78, 9),
 (4, 84, 9),
 (4, 90, 10),
 (5, 99, 11),
 (5, 108, 11),
 (5, 117, 12),
 (5, 126, 13),
 (5, 135, 14),
 (5, 144, 15),
 (5, 153, 16),
 (5, 162, 17),
 (5, 171, 18),
 (5, 180, 18),
 (5, 189, 19),
 (5, 198, 20),
 (5, 207, 21),
 (5, 216, 21),
 (6, 230, 23),
 (7, 231, 23),
 (7, 232, 23),
 (8, 234, 23),
 (8, 236, 23),
 (9, 238, 23),
 (9, 240, 23),
 (9, 242, 23),
 (9, 244, 23),
 (10, 248, 24),
 (10, 252, 24),
 (10, 256, 24),
 (10, 260, 24),
 (10, 264, 24),
 (10, 268, 24),
 (11, 274, 25),
 (11, 280, 25),
 (11, 286, 26),
 (11, 292, 26),
 (11, 298, 26),
 (11, 304, 27),
 (11, 310, 27),
 (11, 316, 28),
 (11, 322, 28),
 (12, 331, 29),
 (12, 340, 30),
 (12, 349, 30),
 (12, 358, 31),
 (12, 367, 32),
 (12, 376, 33),
 (12, 385, 33),
 (12, 394, 34),
 (12, 403, 34),
 (12, 412, 35),
 (12, 421, 36),
 (12, 430, 36),
 (12, 439, 37),
 (12, 448, 37),
 (13, 462, 38),
 (14, 463, 38),
 (14, 464, 38),
 (15, 466, 38),
 (15, 468, 39),
 (16, 470, 39),
 (16, 472, 39),
 (16, 474, 39),
 (16, 476, 39),
 (17, 480, 39),
 (17, 484, 39),
 (17, 488, 39),
 (17, 492, 40),
 (17, 496, 40),
 (17, 500, 40),
 (18, 506, 41),
 (18, 512, 41),
 (18, 518, 23),
 (18, 524, 23),
 (18, 530, 42),
 (18, 536, 42),
 (18, 542, 42),
 (18, 548, 43),
 (18, 554, 44),
 (19, 563, 45),
 (19, 572, 46),
 (19, 581, 46),
 (19, 590, 47),
 (19, 599, 48),
 (19, 608, 48),
 (19, 617, 49),
 (19, 626, 51),
 (19, 635, 51),
 (19, 644, 51),
 (19, 653, 52),
 (19, 662, 53),
 (19, 671, 53),
 (19, 680, 54),
 (20, 694, 54),
 (21, 695, 55),
 (21, 696, 55),
 (22, 698, 55),
 (22, 700, 55),
 (23, 702, 55),
 (23, 704, 55),
 (23, 706, 55),
 (23, 708, 55),
 (24, 712, 55),
 (24, 716, 56),
 (24, 720, 56),
 (24, 724, 56),
 (24, 728, 56),
 (24, 732, 57),
 (25, 738, 57),
 (25, 744, 57),
 (25, 750, 58),
 (25, 756, 59),
 (25, 762, 60),
 (25, 768, 61),
 (25, 774, 61),
 (25, 780, 62),
 (25, 786, 63),
 (26, 795, 63),
 (26, 804, 64),
 (26, 813, 65),
 (26, 822, 66),
 (26, 831, 67),
 (26, 840, 67),
 (26, 849, 68),
 (26, 858, 69),
 (26, 867, 70),
 (26, 876, 70),
 (26, 885, 71),
 (26, 894, 72),
 (26, 903, 72),
 (26, 912, 73),
 (27, 926, 74),
 (28, 927, 74),
 (28, 928, 74),
 (29, 930, 74),
 (29, 932, 74),
 (30, 934, 74),
 (30, 936, 75),
 (30, 938, 75),
 (30, 940, 75),
 (31, 944, 75),
 (31, 948, 75),
 (31, 952, 76),
 (31, 956, 76),
 (31, 960, 76),
 (31, 964, 77),
 (32, 970, 77),
 (32, 976, 78),
 (32, 982, 78),
 (32, 988, 78),
 (32, 994, 79),
 (32, 1000, 80),
 (32, 1006, 80),
 (32, 1012, 81),
 (32, 1018, 81),
 (33, 1027, 82),
 (33, 1036, 83),
 (33, 1045, 83),
 (33, 1054, 83),
 (33, 1063, 84),
 (33, 1072, 84),
 (33, 1081, 85),
 (33, 1090, 86),
 (33, 1099, 86),
 (33, 1108, 73),
 (33, 1117, 73),
 (33, 1126, 88),
 (33, 1135, 89),
 (33, 1144, 89),
 (34, 1158, 91),
 (35, 1159, 91),
 (35, 1160, 91),
 (36, 1162, 91),
 (36, 1164, 91),
 (37, 1166, 91),
 (37, 1168, 91),
 (37, 1170, 91),
 (37, 1172, 91),
 (38, 1176, 92),
 (38, 1180, 92),
 (38, 1184, 92),
 (38, 1188, 93),
 (38, 1192, 93),
 (38, 1196, 93),
 (39, 1202, 94),
 (39, 1208, 94),
 (39, 1214, 95),
 (39, 1220, 95),
 (39, 1226, 96),
 (39, 1232, 96),
 (39, 1238, 97),
 (39, 1244, 97),
 (39, 1250, 98),
 (40, 1259, 99),
 (40, 1268, 100),
 (40, 1277, 101),
 (40, 1286, 101),
 (40, 1295, 102),
 (40, 1304, 102),
 (40, 1313, 103),
 (40, 1322, 104),
 (40, 1331, 105),
 (40, 1340, 106),
 (40, 1349, 107),
 (40, 1358, 108),
 (40, 1367, 109),
 (40, 1376, 110),
 (41, 1390, 112),
 (42, 1391, 112),
 (42, 1392, 112),
 (43, 1394, 112),
 (43, 1396, 113),
 (44, 1398, 113),
 (44, 1400, 113),
 (44, 1402, 113),
 (44, 1404, 113),
 (45, 1408, 114),
 (45, 1412, 114),
 (45, 1416, 115),
 (45, 1420, 115),
 (45, 1424, 115),
 (45, 1428, 115),
 (46, 1434, 116),
 (46, 1440, 116),
 (46, 1446, 117),
 (46, 1452, 117),
 (46, 1458, 118),
 (46, 1464, 118),
 (46, 1470, 119),
 (46, 1476, 119),
 (46, 1482, 120),
 (47, 1491, 120),
 (47, 1500, 121),
 (47, 1509, 122),
 (47, 1518, 122),
 (47, 1527, 123),
 (47, 1536, 124),
 (47, 1545, 124),
 (47, 1554, 125),
 (47, 1563, 126),
 (47, 1572, 126),
 (47, 1581, 127),
 (47, 1590, 128),
 (47, 1599, 129),
 (47, 1608, 130),
 (48, 1622, 132),
 (49, 1623, 132),
 (49, 1624, 132),
 (50, 1626, 132),
 (50, 1628, 133),
 (51, 1630, 133),
 (51, 1632, 133),
 (51, 1634, 133),
 (51, 1636, 134),
 (52, 1640, 134),
 (52, 1644, 134),
 (52, 1648, 135),
 (52, 1652, 135),
 (52, 1656, 136),
 (52, 1660, 136),
 (53, 1666, 137),
 (53, 1672, 139),
 (53, 1678, 139),
 (53, 1684, 139),
 (53, 1690, 140),
 (53, 1696, 140),
 (53, 1702, 141),
 (53, 1708, 141),
 (53, 1714, 141),
 (54, 1723, 142),
 (54, 1732, 143),
 (54, 1741, 143),
 (54, 1750, 144),
 (54, 1759, 145),
 (54, 1768, 145),
 (54, 1777, 146),
 (54, 1786, 146),
 (54, 1795, 147),
 (54, 1804, 148),
 (54, 1813, 149),
 (54, 1822, 149),
 (54, 1831, 150),
 (54, 1840, 151),
 (55, 1854, 152),
 (56, 1855, 152),
 (56, 1856, 152),
 (57, 1858, 152),
 (57, 1860, 152),
 (58, 1862, 153),
 (58, 1864, 153),
 (58, 1866, 153),
 (58, 1868, 153),
 (59, 1872, 153),
 (59, 1876, 154),
 (59, 1880, 154),
 (59, 1884, 155),
 (59, 1888, 155),
 (59, 1892, 155),
 (60, 1898, 156),
 (60, 1904, 157),
 (60, 1910, 157),
 (60, 1916, 158),
 (60, 1922, 158),
 (60, 1928, 158),
 (60, 1934, 159),
 (60, 1940, 159),
 (60, 1946, 160),
 (61, 1955, 160),
 (61, 1964, 161),
 (61, 1973, 162),
 (61, 1982, 162),
 (61, 1991, 163),
 (61, 2000, 163),
 (61, 2009, 164),
 (61, 2018, 165),
 (61, 2027, 165),
 (61, 2036, 166),
 (61, 2045, 167),
 (61, 2054, 167),
 (61, 2063, 167),
 (61, 2072, 168),
 (62, 2086, 169),
 (63, 2087, 169),
 (63, 2088, 169),
 (64, 2090, 169),
 (64, 2092, 169),
 (65, 2094, 171),
 (65, 2096, 172),
 (65, 2098, 173),
 (65, 2100, 174),
 (66, 2104, 174),
 (66, 2108, 174),
 (66, 2112, 174),
 (66, 2116, 175),
 (66, 2120, 175),
 (66, 2124, 175),
 (67, 2130, 176),
 (67, 2136, 176),
 (67, 2142, 177),
 (67, 2148, 177),
 (67, 2154, 178),
 (67, 2160, 178),
 (67, 2166, 179),
 (67, 2172, 179),
 (67, 2178, 180),
 (68, 2187, 180),
 (68, 2196, 181),
 (68, 2205, 182),
 (68, 2214, 182),
 (68, 2223, 141),
 (68, 2232, 183),
 (68, 2241, 184),
 (68, 2250, 184),
 (68, 2259, 185),
 (68, 2268, 185),
 (68, 2277, 186),
 (68, 2286, 188),
 (68, 2295, 188),
 (68, 2304, 189),
 (69, 2318, 190),
 (70, 2319, 190),
 (70, 2320, 190),
 (71, 2322, 190),
 (71, 2324, 190),
 (72, 2326, 190),
 (72, 2328, 190),
 (72, 2330, 190),
 (72, 2332, 190),
 (73, 2336, 191),
 (73, 2340, 191),
 (73, 2344, 192),
 (73, 2348, 192),
 (73, 2352, 192),
 (73, 2356, 192),
 (74, 2362, 193),
 (74, 2368, 193),
 (74, 2374, 193),
 (74, 2380, 194),
 (74, 2386, 194),
 (74, 2392, 195),
 (74, 2398, 195),
 (74, 2404, 195),
 (74, 2410, 196),
 (75, 2419, 196),
 (75, 2428, 198),
 (75, 2437, 141),
 (75, 2446, 141),
 (75, 2455, 199),
 (75, 2464, 200),
 (75, 2473, 201),
 (75, 2482, 201),
 (75, 2491, 202),
 (75, 2500, 202),
 (75, 2509, 203),
 (75, 2518, 203),
 (75, 2527, 204),
 (75, 2536, 205),
 (76, 2550, 206),
 (77, 2551, 206),
 (77, 2552, 206),
 (78, 2554, 207),
 (78, 2556, 207),
 (79, 2558, 207),
 (79, 2560, 207),
 (79, 2562, 207),
 (79, 2564, 207),
 (80, 2568, 208),
 (80, 2572, 209),
 (80, 2576, 209),
 (80, 2580, 209),
 (80, 2584, 210),
 (80, 2588, 210),
 (81, 2594, 211),
 (81, 2600, 211),
 (81, 2606, 211),
 (81, 2612, 212),
 (81, 2618, 212),
 (81, 2624, 213),
 (81, 2630, 213),
 (81, 2636, 213),
 (81, 2642, 214),
 (82, 2651, 215),
 (82, 2660, 215),
 (82, 2669, 216),
 (82, 2678, 217),
 (82, 2687, 217),
 (82, 2696, 218),
 (82, 2705, 219),
 (82, 2714, 219),
 (82, 2723, 220),
 (82, 2732, 221),
 (82, 2741, 221),
 (82, 2750, 221),
 (82, 2759, 222),
 (82, 2768, 223),
 (83, 2782, 224),
 (84, 2783, 224),
 (84, 2784, 224),
 (85, 2786, 224),
 (85, 2788, 224),
 (86, 2790, 224),
 (86, 2792, 224),
 (86, 2794, 224),
 (86, 2796, 224),
 (87, 2800, 224),
 (87, 2804, 225),
 (87, 2808, 225),
 (87, 2812, 225),
 (87, 2816, 225),
 (87, 2820, 227),
 (88, 2826, 227),
 (88, 2832, 227),
 (88, 2838, 227),
 (88, 2844, 228),
 (88, 2850, 228),
 (88, 2856, 228),
 (88, 2862, 229),
 (88, 2868, 230),
 (88, 2874, 229),
 (89, 2883, 230),
 (89, 2892, 231),
 (89, 2901, 230),
 (89, 2910, 231),
 (89, 2919, 230),
 (89, 2928, 232),
 (89, 2937, 232),
 (89, 2946, 233),
 (89, 2955, 234),
 (89, 2964, 235),
 (89, 2973, 235),
 (89, 2982, 236),
 (89, 2991, 237),
 (89, 3000, 237),
 (90, 3014, 238),
 (91, 3015, 238),
 (91, 3016, 238),
 (92, 3018, 239),
 (92, 3020, 239),
 (93, 3022, 239),
 (93, 3024, 239),
 (93, 3026, 239),
 (93, 3028, 240),
 (94, 3032, 240),
 (94, 3036, 240),
 (94, 3040, 241),
 (94, 3044, 241),
 (94, 3048, 241),
 (94, 3052, 242),
 (95, 3058, 242),
 (95, 3064, 243),
 (95, 3070, 243),
 (95, 3076, 243),
 (95, 3082, 244),
 (95, 3088, 244),
 (95, 3094, 245),
 (95, 3100, 245),
 (95, 3106, 246),
 (96, 3115, 246),
 (96, 3124, 247),
 (96, 3133, 141),
 (96, 3142, 141),
 (96, 3151, 248),
 (96, 3160, 248),
 (96, 3169, 229),
 (96, 3178, 250),
 (96, 3187, 250),
 (96, 3196, 250),
 (96, 3205, 251),
 (96, 3214, 251),
 (96, 3223, 228),
 (96, 3232, 253),
 (97, 3246, 253),
 (98, 3247, 253),
 (98, 3248, 253),
 (99, 3250, 254),
 (99, 3252, 229),
 (100, 3254, 255),
 (100, 3256, 255),
 (100, 3258, 255),
 (100, 3260, 255),
 (101, 3264, 255),
 (101, 3268, 255),
 (101, 3272, 255),
 (101, 3276, 256),
 (101, 3280, 256),
 (101, 3284, 256),
 (102, 3290, 257),
 (102, 3296, 257),
 (102, 3302, 258),
 (102, 3308, 258),
 (102, 3314, 258),
 (102, 3320, 259),
 (102, 3326, 259),
 (102, 3332, 259),
 (102, 3338, 261),
 (103, 3347, 261),
 (103, 3356, 266),
 (103, 3365, 269),
 (103, 3374, 269),
 (103, 3383, 270),
 (103, 3392, 271),
 (103, 3401, 271),
 (103, 3410, 279),
 (103, 3419, 288),
 (103, 3428, 251),
 (103, 3437, 304),
 (103, 3446, 312),
 (103, 3455, 321),
 (103, 3464, 321),
 (104, 3478, 323),
 (105, 3479, 324),
 (105, 3480, 325),
 (106, 3482, 327),
 (106, 3484, 329),
 (107, 3486, 331),
 (107, 3488, 333),
 (107, 3490, 335),
 (107, 3492, 314),
 (108, 3496, 340),
 (108, 3500, 344),
 (108, 1, 1),
 (108, 5, 3),
 (108, 9, 1),
 (108, 13, 1),
 (109, 19, 4),
 (109, 25, 5),
 (109, 31, 5),
 (109, 37, 5),
 (109, 43, 6),
 (109, 49, 6),
 (109, 55, 7),
 (109, 61, 7),
 (109, 67, 8),
 (110, 76, 8),
 (110, 85, 10),
 (110, 94, 10),
 (110, 103, 11),
 (110, 112, 12),
 (110, 121, 12),
 (110, 130, 13),
 (110, 139, 14),
 (110, 148, 15),
 (110, 157, 17),
 (110, 166, 18),
 (110, 175, 18),
 (110, 184, 19),
 (110, 193, 19),
 (111, 207, 21),
 (112, 208, 21),
 (112, 209, 21),
 (113, 211, 21),
 (113, 213, 21),
 (114, 215, 21),
 (114, 217, 21),
 (114, 219, 21),
 (114, 221, 21),
 (115, 225, 22),
 (115, 229, 23),
 (115, 233, 23),
 (115, 237, 23),
 (115, 241, 23),
 (115, 245, 23),
 (116, 251, 24),
 (116, 257, 24),
 (116, 263, 24),
 (116, 269, 25),
 (116, 275, 25),
 (116, 281, 25),
 (116, 287, 26),
 (116, 293, 26),
 (116, 299, 27),
 (117, 308, 27),
 (117, 317, 28),
 (117, 326, 29),
 (117, 335, 29),
 (117, 344, 30),
 (117, 353, 31),
 (117, 362, 32),
 (117, 371, 32),
 (117, 380, 33),
 (117, 389, 33),
 (117, 398, 34),
 (117, 407, 34),
 (117, 416, 35),
 (117, 425, 36),
 (118, 439, 37),
 (119, 440, 37),
 (119, 441, 37),
 (120, 443, 37),
 (120, 445, 37),
 (121, 447, 37),
 (121, 449, 37),
 (121, 451, 37),
 (121, 453, 37),
 (122, 457, 38),
 (122, 461, 38),
 (122, 465, 38),
 (122, 469, 39),
 (122, 473, 39),
 (122, 477, 39),
 (123, 483, 39),
 (123, 489, 40),
 (123, 495, 40),
 (123, 501, 41),
 (123, 507, 41),
 (123, 513, 41),
 (123, 519, 23),
 (123, 525, 23),
 (123, 531, 42),
 (124, 540, 42),
 (124, 549, 43),
 (124, 558, 45),
 (124, 567, 45),
 (124, 576, 46),
 (124, 585, 47),
 (124, 594, 47),
 (124, 603, 48),
 (124, 612, 49),
 (124, 621, 50),
 (124, 630, 51),
 (124, 639, 51),
 (124, 648, 52),
 (124, 657, 52),
 (125, 671, 53),
 (126, 672, 53),
 (126, 673, 53),
 (127, 675, 54),
 (127, 677, 54),
 (128, 679, 54),
 (128, 681, 54),
 (128, 683, 54),
 (128, 685, 54),
 (129, 689, 54),
 (129, 693, 54),
 (129, 697, 55),
 (129, 701, 55),
 (129, 705, 55),
 (129, 709, 55),
 (130, 715, 56),
 (130, 721, 56),
 (130, 727, 56),
 (130, 733, 57),
 (130, 739, 57),
 (130, 745, 58),
 (130, 751, 58),
 (130, 757, 59),
 (130, 763, 60),
 (131, 772, 61),
 (131, 781, 62),
 (131, 790, 63),
 (131, 799, 64),
 (131, 808, 65),
 (131, 817, 66),
 (131, 826, 67),
 (131, 835, 67),
 (131, 844, 68),
 (131, 853, 69),
 (131, 862, 69),
 (131, 871, 70),
 (131, 880, 71),
 (131, 889, 71),
 (132, 903, 72),
 (133, 904, 72),
 (133, 905, 72),
 (134, 907, 72),
 (134, 909, 73),
 (135, 911, 73),
 (135, 913, 73),
 (135, 915, 73),
 (135, 917, 73),
 (136, 921, 73),
 (136, 925, 74),
 (136, 929, 74),
 (136, 933, 74),
 (136, 937, 75),
 (136, 941, 75),
 (137, 947, 75),
 (137, 953, 76),
 (137, 959, 76),
 (137, 965, 77),
 (137, 971, 77),
 (137, 977, 78),
 (137, 983, 78),
 (137, 989, 79),
 (137, 995, 79),
 (138, 1004, 80),
 (138, 1013, 81),
 (138, 1022, 82),
 (138, 1031, 82),
 (138, 1040, 83),
 (138, 1049, 83),
 (138, 1058, 84),
 (138, 1067, 84),
 (138, 1076, 85),
 (138, 1085, 85),
 (138, 1094, 86),
 (138, 1103, 87),
 (138, 1112, 73),
 (138, 1121, 88),
 (139, 1135, 89),
 (140, 1136, 89),
 (140, 1137, 89),
 (141, 1139, 89),
 (141, 1141, 89),
 (142, 1143, 89),
 (142, 1145, 89),
 (142, 1147, 90),
 (142, 1149, 90),
 (143, 1153, 90),
 (143, 1157, 90),
 (143, 1161, 91),
 (143, 1165, 91),
 (143, 1169, 91),
 (143, 1173, 91),
 (144, 1179, 92),
 (144, 1185, 92),
 (144, 1191, 93),
 (144, 1197, 93),
 (144, 1203, 94),
 (144, 1209, 94),
 (144, 1215, 95),
 (144, 1221, 95),
 (144, 1227, 96),
 (145, 1236, 97),
 (145, 1245, 98),
 (145, 1254, 98),
 (145, 1263, 99),
 (145, 1272, 100),
 (145, 1281, 101),
 (145, 1290, 102),
 (145, 1299, 102),
 (145, 1308, 103),
 (145, 1317, 104),
 (145, 1326, 105),
 (145, 1335, 106),
 (145, 1344, 107),
 (145, 1353, 108),
 (146, 1367, 109),
 (147, 1368, 109),
 (147, 1369, 109),
 (148, 1371, 110),
 (148, 1373, 110),
 (149, 1375, 110),
 (149, 1377, 110),
 (149, 1379, 111),
 (149, 1381, 111),
 (150, 1385, 111),
 (150, 1389, 112),
 (150, 1393, 112),
 (150, 1397, 113),
 (150, 1401, 113),
 (150, 1405, 113),
 (151, 1411, 114),
 (151, 1417, 115),
 (151, 1423, 115),
 (151, 1429, 115),
 (151, 1435, 116),
 (151, 1441, 116),
 (151, 1447, 117),
 (151, 1453, 117),
 (151, 1459, 118),
 (152, 1468, 119),
 (152, 1477, 119),
 (152, 1486, 120),
 (152, 1495, 120),
 (152, 1504, 121),
 (152, 1513, 122),
 (152, 1522, 123),
 (152, 1531, 123),
 (152, 1540, 124),
 (152, 1549, 125),
 (152, 1558, 125),
 (152, 1567, 126),
 (152, 1576, 126),
 (152, 1585, 127),
 (153, 1599, 129),
 (154, 1600, 129),
 (154, 1601, 129),
 (155, 1603, 130),
 (155, 1605, 130),
 (156, 1607, 130),
 (156, 1609, 130),
 (156, 1611, 131),
 (156, 1613, 131),
 (157, 1617, 131),
 (157, 1621, 132),
 (157, 1625, 132),
 (157, 1629, 133),
 (157, 1633, 133),
 (157, 1637, 134),
 (158, 1643, 134),
 (158, 1649, 135),
 (158, 1655, 136),
 (158, 1661, 136),
 (158, 1667, 138),
 (158, 1673, 139),
 (158, 1679, 139),
 (158, 1685, 139),
 (158, 1691, 140),
 (159, 1700, 140),
 (159, 1709, 141),
 (159, 1718, 143),
 (159, 1727, 142),
 (159, 1736, 142),
 (159, 1745, 144),
 (159, 1754, 144),
 (159, 1763, 145),
 (159, 1772, 145),
 (159, 1781, 146),
 (159, 1790, 146),
 (159, 1799, 147),
 (159, 1808, 148),
 (159, 1817, 149),
 (160, 1831, 150),
 (161, 1832, 150),
 (161, 1833, 150),
 (162, 1835, 150),
 (162, 1837, 150),
 (163, 1839, 151),
 (163, 1841, 151),
 (163, 1843, 151),
 (163, 1845, 151),
 (164, 1849, 151),
 (164, 1853, 152),
 (164, 1857, 152),
 (164, 1861, 153),
 (164, 1865, 153),
 (164, 1869, 153),
 (165, 1875, 154),
 (165, 1881, 154),
 (165, 1887, 155),
 (165, 1893, 156),
 (165, 1899, 156),
 (165, 1905, 157),
 (165, 1911, 157),
 (165, 1917, 158),
 (165, 1923, 158),
 (166, 1932, 159),
 (166, 1941, 159),
 (166, 1950, 160),
 (166, 1959, 161),
 (166, 1968, 161),
 (166, 1977, 162),
 (166, 1986, 163),
 (166, 1995, 163),
 (166, 2004, 164),
 (166, 2013, 164),
 (166, 2022, 165),
 (166, 2031, 166),
 (166, 2040, 166),
 (166, 2049, 167),
 (167, 2063, 167),
 (168, 2064, 167),
 (168, 2065, 168),
 (169, 2067, 168),
 (169, 2069, 168),
 (170, 2071, 168),
 (170, 2073, 168),
 (170, 2075, 168),
 (170, 2077, 169),
 (171, 2081, 169),
 (171, 2085, 169),
 (171, 2089, 169),
 (171, 2093, 170),
 (171, 2097, 173),
 (171, 2101, 174),
 (172, 2107, 174),
 (172, 2113, 175),
 (172, 2119, 175),
 (172, 2125, 176),
 (172, 2131, 176),
 (172, 2137, 176),
 (172, 2143, 177),
 (172, 2149, 178),
 (172, 2155, 178),
 (173, 2164, 178),
 (173, 2173, 179),
 (173, 2182, 180),
 (173, 2191, 180),
 (173, 2200, 181),
 (173, 2209, 182),
 (173, 2218, 141),
 (173, 2227, 141),
 (173, 2236, 183),
 (173, 2245, 184),
 (173, 2254, 185),
 (173, 2263, 185),
 (173, 2272, 186),
 (173, 2281, 186),
 (174, 2295, 188),
 (175, 2296, 189),
 (175, 2297, 189),
 (176, 2299, 189),
 (176, 2301, 189),
 (177, 2303, 189),
 (177, 2305, 189),
 (177, 2307, 189),
 (177, 2309, 189),
 (178, 2313, 187),
 (178, 2317, 187),
 (178, 2321, 190),
 (178, 2325, 190),
 (178, 2329, 190),
 (178, 2333, 190),
 (179, 2339, 191),
 (179, 2345, 192),
 (179, 2351, 192),
 (179, 2357, 192),
 (179, 2363, 193),
 (179, 2369, 193),
 (179, 2375, 194),
 (179, 2381, 194),
 (179, 2387, 194),
 (180, 2396, 195),
 (180, 2405, 195),
 (180, 2414, 196),
 (180, 2423, 197),
 (180, 2432, 198),
 (180, 2441, 141),
 (180, 2450, 199),
 (180, 2459, 199),
 (180, 2468, 200),
 (180, 2477, 201),
 (180, 2486, 201),
 (180, 2495, 202),
 (180, 2504, 202),
 (180, 2513, 203),
 (181, 2527, 204),
 (182, 2528, 204),
 (182, 2529, 204),
 (183, 2531, 204),
 (183, 2533, 205),
 (184, 2535, 205),
 (184, 2537, 205),
 (184, 2539, 205),
 (184, 2541, 205),
 (185, 2545, 206),
 (185, 2549, 206),
 (185, 2553, 206),
 (185, 2557, 207),
 (185, 2561, 207),
 (185, 2565, 208),
 ...]

From the above table it can be observed that if the tracks belonging to each distinct invoice belongs to the same album it is an Album Purchase. If these tracks belong to different albums it is Non Albu Purchase.

Below, we can categorize these invoices into Album and Non Album Purchase. This can be done by counting the number of distinct albums belonging to each invoice. Then we compare the Distinct Albums and Number of Albums belonging to each invoice.

In [44]:
%%sql

WITH com_prchs AS
(
    SELECT 
       il.InvoiceId invoice_id, 
       il.TrackId Prchs_tracks, 
       t.AlbumId album_id
      FROM tracks t
    INNER JOIN invoice_items il on il.TrackId = t.TrackId
    ORDER BY 1
)

SELECT 
   invoice_id, 
   COUNT(DISTINCT(album_id)) Distinct_album_id,
   COUNT(album_id) No_of_album_id,
   CASE
   WHEN COUNT(album_id) - COUNT(DISTINCT(album_id)) <= 2 THEN "Non Album Purchase"
   ELSE "Album Purchase"
   END AS Category
  FROM com_prchs
 GROUP BY 1;

 * sqlite:///chinook.db
Done.

[(1, 2, 2, 'Non Album Purchase'),
 (2, 1, 4, 'Album Purchase'),
 (3, 2, 6, 'Album Purchase'),
 (4, 5, 9, 'Album Purchase'),
 (5, 11, 14, 'Album Purchase'),
 (6, 1, 1, 'Non Album Purchase'),
 (7, 1, 2, 'Non Album Purchase'),
 (8, 1, 2, 'Non Album Purchase'),
 (9, 1, 4, 'Album Purchase'),
 (10, 1, 6, 'Album Purchase'),
 (11, 4, 9, 'Album Purchase'),
 (12, 9, 14, 'Album Purchase'),
 (13, 1, 1, 'Non Album Purchase'),
 (14, 1, 2, 'Non Album Purchase'),
 (15, 2, 2, 'Non Album Purchase'),
 (16, 1, 4, 'Album Purchase'),
 (17, 2, 6, 'Album Purchase'),
 (18, 5, 9, 'Album Purchase'),
 (19, 9, 14, 'Album Purchase'),
 (20, 1, 1, 'Non Album Purchase'),
 (21, 1, 2, 'Non Album Purchase'),
 (22, 1, 2, 'Non Album Purchase'),
 (23, 1, 4, 'Album Purchase'),
 (24, 3, 6, 'Album Purchase'),
 (25, 7, 9, 'Non Album Purchase'),
 (26, 11, 14, 'Album Purchase'),
 (27, 1, 1, 'Non Album Purchase'),
 (28, 1, 2, 'Non Album Purchase'),
 (29, 1, 2, 'Non Album Purchase'),
 (30, 2, 4, 'Non Album Purchase'),
 (31, 3, 6, 'Album Purchase'),
 (32, 5, 9, 'Album Purchase'),
 (33, 8, 14, 'Album Purchase'),
 (34, 1, 1, 'Non Album Purchase'),
 (35, 1, 2, 'Non Album Purchase'),
 (36, 1, 2, 'Non Album Purchase'),
 (37, 1, 4, 'Album Purchase'),
 (38, 2, 6, 'Album Purchase'),
 (39, 5, 9, 'Album Purchase'),
 (40, 12, 14, 'Non Album Purchase'),
 (41, 1, 1, 'Non Album Purchase'),
 (42, 1, 2, 'Non Album Purchase'),
 (43, 2, 2, 'Non Album Purchase'),
 (44, 1, 4, 'Album Purchase'),
 (45, 2, 6, 'Album Purchase'),
 (46, 5, 9, 'Album Purchase'),
 (47, 11, 14, 'Album Purchase'),
 (48, 1, 1, 'Non Album Purchase'),
 (49, 1, 2, 'Non Album Purchase'),
 (50, 2, 2, 'Non Album Purchase'),
 (51, 2, 4, 'Non Album Purchase'),
 (52, 3, 6, 'Album Purchase'),
 (53, 4, 9, 'Album Purchase'),
 (54, 10, 14, 'Album Purchase'),
 (55, 1, 1, 'Non Album Purchase'),
 (56, 1, 2, 'Non Album Purchase'),
 (57, 1, 2, 'Non Album Purchase'),
 (58, 1, 4, 'Album Purchase'),
 (59, 3, 6, 'Album Purchase'),
 (60, 5, 9, 'Album Purchase'),
 (61, 9, 14, 'Album Purchase'),
 (62, 1, 1, 'Non Album Purchase'),
 (63, 1, 2, 'Non Album Purchase'),
 (64, 1, 2, 'Non Album Purchase'),
 (65, 4, 4, 'Non Album Purchase'),
 (66, 2, 6, 'Album Purchase'),
 (67, 5, 9, 'Album Purchase'),
 (68, 10, 14, 'Album Purchase'),
 (69, 1, 1, 'Non Album Purchase'),
 (70, 1, 2, 'Non Album Purchase'),
 (71, 1, 2, 'Non Album Purchase'),
 (72, 1, 4, 'Album Purchase'),
 (73, 2, 6, 'Album Purchase'),
 (74, 4, 9, 'Album Purchase'),
 (75, 10, 14, 'Album Purchase'),
 (76, 1, 1, 'Non Album Purchase'),
 (77, 1, 2, 'Non Album Purchase'),
 (78, 1, 2, 'Non Album Purchase'),
 (79, 1, 4, 'Album Purchase'),
 (80, 3, 6, 'Album Purchase'),
 (81, 4, 9, 'Album Purchase'),
 (82, 9, 14, 'Album Purchase'),
 (83, 1, 1, 'Non Album Purchase'),
 (84, 1, 2, 'Non Album Purchase'),
 (85, 1, 2, 'Non Album Purchase'),
 (86, 1, 4, 'Album Purchase'),
 (87, 3, 6, 'Album Purchase'),
 (88, 4, 9, 'Album Purchase'),
 (89, 8, 14, 'Album Purchase'),
 (90, 1, 1, 'Non Album Purchase'),
 (91, 1, 2, 'Non Album Purchase'),
 (92, 1, 2, 'Non Album Purchase'),
 (93, 2, 4, 'Non Album Purchase'),
 (94, 3, 6, 'Album Purchase'),
 (95, 5, 9, 'Album Purchase'),
 (96, 9, 14, 'Album Purchase'),
 (97, 1, 1, 'Non Album Purchase'),
 (98, 1, 2, 'Non Album Purchase'),
 (99, 2, 2, 'Non Album Purchase'),
 (100, 1, 4, 'Album Purchase'),
 (101, 2, 6, 'Album Purchase'),
 (102, 4, 9, 'Album Purchase'),
 (103, 11, 14, 'Album Purchase'),
 (104, 1, 1, 'Non Album Purchase'),
 (105, 2, 2, 'Non Album Purchase'),
 (106, 2, 2, 'Non Album Purchase'),
 (107, 4, 4, 'Non Album Purchase'),
 (108, 4, 6, 'Non Album Purchase'),
 (109, 5, 9, 'Album Purchase'),
 (110, 10, 14, 'Album Purchase'),
 (111, 1, 1, 'Non Album Purchase'),
 (112, 1, 2, 'Non Album Purchase'),
 (113, 1, 2, 'Non Album Purchase'),
 (114, 1, 4, 'Album Purchase'),
 (115, 2, 6, 'Album Purchase'),
 (116, 4, 9, 'Album Purchase'),
 (117, 10, 14, 'Album Purchase'),
 (118, 1, 1, 'Non Album Purchase'),
 (119, 1, 2, 'Non Album Purchase'),
 (120, 1, 2, 'Non Album Purchase'),
 (121, 1, 4, 'Album Purchase'),
 (122, 2, 6, 'Album Purchase'),
 (123, 5, 9, 'Album Purchase'),
 (124, 10, 14, 'Album Purchase'),
 (125, 1, 1, 'Non Album Purchase'),
 (126, 1, 2, 'Non Album Purchase'),
 (127, 1, 2, 'Non Album Purchase'),
 (128, 1, 4, 'Album Purchase'),
 (129, 2, 6, 'Album Purchase'),
 (130, 5, 9, 'Album Purchase'),
 (131, 11, 14, 'Album Purchase'),
 (132, 1, 1, 'Non Album Purchase'),
 (133, 1, 2, 'Non Album Purchase'),
 (134, 2, 2, 'Non Album Purchase'),
 (135, 1, 4, 'Album Purchase'),
 (136, 3, 6, 'Album Purchase'),
 (137, 5, 9, 'Album Purchase'),
 (138, 10, 14, 'Album Purchase'),
 (139, 1, 1, 'Non Album Purchase'),
 (140, 1, 2, 'Non Album Purchase'),
 (141, 1, 2, 'Non Album Purchase'),
 (142, 2, 4, 'Non Album Purchase'),
 (143, 2, 6, 'Album Purchase'),
 (144, 5, 9, 'Album Purchase'),
 (145, 12, 14, 'Non Album Purchase'),
 (146, 1, 1, 'Non Album Purchase'),
 (147, 1, 2, 'Non Album Purchase'),
 (148, 1, 2, 'Non Album Purchase'),
 (149, 2, 4, 'Non Album Purchase'),
 (150, 3, 6, 'Album Purchase'),
 (151, 5, 9, 'Album Purchase'),
 (152, 9, 14, 'Album Purchase'),
 (153, 1, 1, 'Non Album Purchase'),
 (154, 1, 2, 'Non Album Purchase'),
 (155, 1, 2, 'Non Album Purchase'),
 (156, 2, 4, 'Non Album Purchase'),
 (157, 4, 6, 'Non Album Purchase'),
 (158, 6, 9, 'Album Purchase'),
 (159, 10, 14, 'Album Purchase'),
 (160, 1, 1, 'Non Album Purchase'),
 (161, 1, 2, 'Non Album Purchase'),
 (162, 1, 2, 'Non Album Purchase'),
 (163, 1, 4, 'Album Purchase'),
 (164, 3, 6, 'Album Purchase'),
 (165, 5, 9, 'Album Purchase'),
 (166, 9, 14, 'Album Purchase'),
 (167, 1, 1, 'Non Album Purchase'),
 (168, 2, 2, 'Non Album Purchase'),
 (169, 1, 2, 'Non Album Purchase'),
 (170, 2, 4, 'Non Album Purchase'),
 (171, 4, 6, 'Non Album Purchase'),
 (172, 5, 9, 'Album Purchase'),
 (173, 10, 14, 'Album Purchase'),
 (174, 1, 1, 'Non Album Purchase'),
 (175, 1, 2, 'Non Album Purchase'),
 (176, 1, 2, 'Non Album Purchase'),
 (177, 1, 4, 'Album Purchase'),
 (178, 2, 6, 'Album Purchase'),
 (179, 4, 9, 'Album Purchase'),
 (180, 10, 14, 'Album Purchase'),
 (181, 1, 1, 'Non Album Purchase'),
 (182, 1, 2, 'Non Album Purchase'),
 (183, 2, 2, 'Non Album Purchase'),
 (184, 1, 4, 'Album Purchase'),
 (185, 3, 6, 'Album Purchase'),
 (186, 5, 9, 'Album Purchase'),
 (187, 9, 14, 'Album Purchase'),
 (188, 1, 1, 'Non Album Purchase'),
 (189, 1, 2, 'Non Album Purchase'),
 (190, 1, 2, 'Non Album Purchase'),
 (191, 1, 4, 'Album Purchase'),
 (192, 2, 6, 'Album Purchase'),
 (193, 3, 9, 'Album Purchase'),
 (194, 7, 14, 'Album Purchase'),
 (195, 1, 1, 'Non Album Purchase'),
 (196, 1, 2, 'Non Album Purchase'),
 (197, 1, 2, 'Non Album Purchase'),
 (198, 2, 4, 'Non Album Purchase'),
 (199, 3, 6, 'Album Purchase'),
 (200, 5, 9, 'Album Purchase'),
 (201, 8, 14, 'Album Purchase'),
 (202, 1, 1, 'Non Album Purchase'),
 (203, 2, 2, 'Non Album Purchase'),
 (204, 1, 2, 'Non Album Purchase'),
 (205, 1, 4, 'Album Purchase'),
 (206, 2, 6, 'Album Purchase'),
 (207, 4, 9, 'Album Purchase'),
 (208, 11, 14, 'Album Purchase'),
 (209, 1, 1, 'Non Album Purchase'),
 (210, 1, 2, 'Non Album Purchase'),
 (211, 1, 2, 'Non Album Purchase'),
 (212, 2, 4, 'Non Album Purchase'),
 (213, 5, 6, 'Non Album Purchase'),
 (214, 6, 9, 'Album Purchase'),
 (215, 11, 14, 'Album Purchase'),
 (216, 1, 1, 'Non Album Purchase'),
 (217, 1, 2, 'Non Album Purchase'),
 (218, 1, 2, 'Non Album Purchase'),
 (219, 2, 4, 'Non Album Purchase'),
 (220, 2, 6, 'Album Purchase'),
 (221, 3, 9, 'Album Purchase'),
 (222, 9, 14, 'Album Purchase'),
 (223, 1, 1, 'Non Album Purchase'),
 (224, 1, 2, 'Non Album Purchase'),
 (225, 1, 2, 'Non Album Purchase'),
 (226, 1, 4, 'Album Purchase'),
 (227, 2, 6, 'Album Purchase'),
 (228, 4, 9, 'Album Purchase'),
 (229, 10, 14, 'Album Purchase'),
 (230, 1, 1, 'Non Album Purchase'),
 (231, 1, 2, 'Non Album Purchase'),
 (232, 1, 2, 'Non Album Purchase'),
 (233, 2, 4, 'Non Album Purchase'),
 (234, 2, 6, 'Album Purchase'),
 (235, 4, 9, 'Album Purchase'),
 (236, 13, 14, 'Non Album Purchase'),
 (237, 1, 1, 'Non Album Purchase'),
 (238, 1, 2, 'Non Album Purchase'),
 (239, 1, 2, 'Non Album Purchase'),
 (240, 2, 4, 'Non Album Purchase'),
 (241, 2, 6, 'Album Purchase'),
 (242, 4, 9, 'Album Purchase'),
 (243, 9, 14, 'Album Purchase'),
 (244, 1, 1, 'Non Album Purchase'),
 (245, 1, 2, 'Non Album Purchase'),
 (246, 1, 2, 'Non Album Purchase'),
 (247, 2, 4, 'Non Album Purchase'),
 (248, 3, 6, 'Album Purchase'),
 (249, 5, 9, 'Album Purchase'),
 (250, 11, 14, 'Album Purchase'),
 (251, 1, 1, 'Non Album Purchase'),
 (252, 1, 2, 'Non Album Purchase'),
 (253, 1, 2, 'Non Album Purchase'),
 (254, 1, 4, 'Album Purchase'),
 (255, 3, 6, 'Album Purchase'),
 (256, 5, 9, 'Album Purchase'),
 (257, 10, 14, 'Album Purchase'),
 (258, 1, 1, 'Non Album Purchase'),
 (259, 1, 2, 'Non Album Purchase'),
 (260, 1, 2, 'Non Album Purchase'),
 (261, 2, 4, 'Non Album Purchase'),
 (262, 4, 6, 'Non Album Purchase'),
 (263, 7, 9, 'Non Album Purchase'),
 (264, 8, 14, 'Album Purchase'),
 (265, 1, 1, 'Non Album Purchase'),
 (266, 1, 2, 'Non Album Purchase'),
 (267, 2, 2, 'Non Album Purchase'),
 (268, 1, 4, 'Album Purchase'),
 (269, 3, 6, 'Album Purchase'),
 (270, 6, 9, 'Album Purchase'),
 (271, 9, 14, 'Album Purchase'),
 (272, 1, 1, 'Non Album Purchase'),
 (273, 1, 2, 'Non Album Purchase'),
 (274, 1, 2, 'Non Album Purchase'),
 (275, 1, 4, 'Album Purchase'),
 (276, 3, 6, 'Album Purchase'),
 (277, 5, 9, 'Album Purchase'),
 (278, 10, 14, 'Album Purchase'),
 (279, 1, 1, 'Non Album Purchase'),
 (280, 1, 2, 'Non Album Purchase'),
 (281, 1, 2, 'Non Album Purchase'),
 (282, 3, 4, 'Non Album Purchase'),
 (283, 3, 6, 'Album Purchase'),
 (284, 5, 9, 'Album Purchase'),
 (285, 10, 14, 'Album Purchase'),
 (286, 1, 1, 'Non Album Purchase'),
 (287, 2, 2, 'Non Album Purchase'),
 (288, 1, 2, 'Non Album Purchase'),
 (289, 1, 4, 'Album Purchase'),
 (290, 4, 6, 'Non Album Purchase'),
 (291, 6, 9, 'Album Purchase'),
 (292, 10, 14, 'Album Purchase'),
 (293, 1, 1, 'Non Album Purchase'),
 (294, 1, 2, 'Non Album Purchase'),
 (295, 1, 2, 'Non Album Purchase'),
 (296, 1, 4, 'Album Purchase'),
 (297, 2, 6, 'Album Purchase'),
 (298, 4, 9, 'Album Purchase'),
 (299, 8, 14, 'Album Purchase'),
 (300, 1, 1, 'Non Album Purchase'),
 (301, 1, 2, 'Non Album Purchase'),
 (302, 1, 2, 'Non Album Purchase'),
 (303, 1, 4, 'Album Purchase'),
 (304, 3, 6, 'Album Purchase'),
 (305, 5, 9, 'Album Purchase'),
 (306, 10, 14, 'Album Purchase'),
 (307, 1, 1, 'Non Album Purchase'),
 (308, 1, 2, 'Non Album Purchase'),
 (309, 1, 2, 'Non Album Purchase'),
 (310, 1, 4, 'Album Purchase'),
 (311, 2, 6, 'Album Purchase'),
 (312, 5, 9, 'Album Purchase'),
 (313, 9, 14, 'Album Purchase'),
 (314, 1, 1, 'Non Album Purchase'),
 (315, 2, 2, 'Non Album Purchase'),
 (316, 2, 2, 'Non Album Purchase'),
 (317, 4, 4, 'Non Album Purchase'),
 (318, 4, 6, 'Non Album Purchase'),
 (319, 8, 9, 'Non Album Purchase'),
 (320, 11, 14, 'Album Purchase'),
 (321, 1, 1, 'Non Album Purchase'),
 (322, 1, 2, 'Non Album Purchase'),
 (323, 2, 2, 'Non Album Purchase'),
 (324, 1, 4, 'Album Purchase'),
 (325, 3, 6, 'Album Purchase'),
 (326, 4, 9, 'Album Purchase'),
 (327, 10, 14, 'Album Purchase'),
 (328, 1, 1, 'Non Album Purchase'),
 (329, 1, 2, 'Non Album Purchase'),
 (330, 1, 2, 'Non Album Purchase'),
 (331, 1, 4, 'Album Purchase'),
 (332, 2, 6, 'Album Purchase'),
 (333, 3, 9, 'Album Purchase'),
 (334, 10, 14, 'Album Purchase'),
 (335, 1, 1, 'Non Album Purchase'),
 (336, 1, 2, 'Non Album Purchase'),
 (337, 1, 2, 'Non Album Purchase'),
 (338, 1, 4, 'Album Purchase'),
 (339, 3, 6, 'Album Purchase'),
 (340, 4, 9, 'Album Purchase'),
 (341, 12, 14, 'Non Album Purchase'),
 (342, 1, 1, 'Non Album Purchase'),
 (343, 1, 2, 'Non Album Purchase'),
 (344, 1, 2, 'Non Album Purchase'),
 (345, 1, 4, 'Album Purchase'),
 (346, 3, 6, 'Album Purchase'),
 (347, 5, 9, 'Album Purchase'),
 (348, 10, 14, 'Album Purchase'),
 (349, 1, 1, 'Non Album Purchase'),
 (350, 1, 2, 'Non Album Purchase'),
 (351, 1, 2, 'Non Album Purchase'),
 (352, 2, 4, 'Non Album Purchase'),
 (353, 2, 6, 'Album Purchase'),
 (354, 4, 9, 'Album Purchase'),
 (355, 11, 14, 'Album Purchase'),
 (356, 1, 1, 'Non Album Purchase'),
 (357, 1, 2, 'Non Album Purchase'),
 (358, 1, 2, 'Non Album Purchase'),
 (359, 2, 4, 'Non Album Purchase'),
 (360, 3, 6, 'Album Purchase'),
 (361, 6, 9, 'Album Purchase'),
 (362, 10, 14, 'Album Purchase'),
 (363, 1, 1, 'Non Album Purchase'),
 (364, 1, 2, 'Non Album Purchase'),
 (365, 1, 2, 'Non Album Purchase'),
 (366, 2, 4, 'Non Album Purchase'),
 (367, 3, 6, 'Album Purchase'),
 (368, 6, 9, 'Album Purchase'),
 (369, 9, 14, 'Album Purchase'),
 (370, 1, 1, 'Non Album Purchase'),
 (371, 1, 2, 'Non Album Purchase'),
 (372, 2, 2, 'Non Album Purchase'),
 (373, 1, 4, 'Album Purchase'),
 (374, 2, 6, 'Album Purchase'),
 (375, 5, 9, 'Album Purchase'),
 (376, 10, 14, 'Album Purchase'),
 (377, 1, 1, 'Non Album Purchase'),
 (378, 1, 2, 'Non Album Purchase'),
 (379, 1, 2, 'Non Album Purchase'),
 (380, 2, 4, 'Non Album Purchase'),
 (381, 2, 6, 'Album Purchase'),
 (382, 5, 9, 'Album Purchase'),
 (383, 10, 14, 'Album Purchase'),
 (384, 1, 1, 'Non Album Purchase'),
 (385, 1, 2, 'Non Album Purchase'),
 (386, 2, 2, 'Non Album Purchase'),
 (387, 1, 4, 'Album Purchase'),
 (388, 4, 6, 'Non Album Purchase'),
 (389, 5, 9, 'Album Purchase'),
 (390, 10, 14, 'Album Purchase'),
 (391, 1, 1, 'Non Album Purchase'),
 (392, 1, 2, 'Non Album Purchase'),
 (393, 1, 2, 'Non Album Purchase'),
 (394, 1, 4, 'Album Purchase'),
 (395, 2, 6, 'Album Purchase'),
 (396, 6, 9, 'Album Purchase'),
 (397, 9, 14, 'Album Purchase'),
 (398, 1, 1, 'Non Album Purchase'),
 (399, 1, 2, 'Non Album Purchase'),
 (400, 1, 2, 'Non Album Purchase'),
 (401, 1, 4, 'Album Purchase'),
 (402, 2, 6, 'Album Purchase'),
 (403, 4, 9, 'Album Purchase'),
 (404, 7, 14, 'Album Purchase'),
 (405, 1, 1, 'Non Album Purchase'),
 (406, 1, 2, 'Non Album Purchase'),
 (407, 1, 2, 'Non Album Purchase'),
 (408, 1, 4, 'Album Purchase'),
 (409, 3, 6, 'Album Purchase'),
 (410, 4, 9, 'Album Purchase'),
 (411, 9, 14, 'Album Purchase'),
 (412, 1, 1, 'Non Album Purchase')]

### Category: Not an Album Purchase

Here we calculate the Percentage of Non Album Purchases for the company.

In [51]:
%%sql

WITH com_prchs AS
(SELECT il.InvoiceId invoice_id, il.TrackId Pur_tracks, t.AlbumId album_id
  FROM tracks t
INNER JOIN invoice_items il ON il.TrackId = t.TrackId
ORDER BY 1
),

ctgr_prchs AS
(SELECT invoice_id, COUNT(DISTINCT(album_id)) Distinct_album_id, 
       COUNT(album_id) No_of_album_id,
       CASE
       WHEN COUNT(album_id) - COUNT(DISTINCT(album_id)) <= 2 THEN "Non Album Purchase"
       ELSE "Album Purchase"
       END AS Category 
  FROM com_prchs
GROUP BY 1
)

SELECT (SELECT MAX(InvoiceId)
          FROM invoice_items) TOTAL_invoice_id,
       COUNT(invoice_id) No_of_invoice_id,
       (SELECT ROUND(CAST(COUNT(invoice_id) AS FLOAT) * 100 / (SELECT MAX(invoice_id)
                                            FROM invoice_items), 2)) Perc_invoice
  FROM ctgr_prchs
WHERE Category = "Non Album Purchase";

 * sqlite:///chinook.db
Done.

[(412, 213, 51.7)]

From the above table, it can be seen that nearly half of the purchases, i.e., 213 out of 412 are Non Album Purchase.

### Category: Album Purchase

Here we calculate the Percentage of Album Purchase for the company.

In [53]:
%%sql

WITH com_prchs AS
(SELECT il.InvoiceId invoice_id, il.TrackId Pur_tracks, t.AlbumId album_id
  FROM tracks t
INNER JOIN invoice_items il ON il.TrackId = t.TrackId
ORDER BY 1
),

ctgr_prchs AS
(SELECT invoice_id, COUNT(DISTINCT(album_id)) Distinct_album_id, 
       COUNT(album_id) No_of_album_id,
       CASE
       WHEN COUNT(album_id) - COUNT(DISTINCT(album_id)) <= 2 THEN "Non Album Purchase"
       ELSE "Album Purchase"
       END AS Category 
  FROM com_prchs
GROUP BY 1
)

SELECT (SELECT MAX(InvoiceId)
          FROM invoice_items) TOTAL_invoice_id,
       COUNT(invoice_id) No_of_invoice_id,
       (SELECT ROUND(CAST(COUNT(invoice_id) AS FLOAT) * 100 / (SELECT MAX(invoice_id)
                                            FROM invoice_items), 2)) Perc_invoice
  FROM ctgr_prchs
WHERE Category = "Album Purchase";

 * sqlite:///chinook.db
Done.

[(412, 199, 48.42)]

Here, it can be seen that nearly 48%, i.e., 199 out of 412 purchase are Album Purchases.

From the above two intepretations, it can be seen that Non Album Purchases slightly sell better. The store should consider buying popular tracks from albums rather than buying the whole album.